apiVersion: apps/v1
kind: Deployment
metadata:
  name: alfavox-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alfavox
  template:
    metadata:
      labels:
        app: alfavox
    spec:
      containers:
      - name: alfavox-container
        image: alfavox-portfolio:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: alfavox-service
spec:
  selector:
    app: alfavox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
